name: survival_list
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+11

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.1
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  firebase_core: ^2.6.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  formz: ^0.5.0+1
  grpc: ^3.1.0
  grpc_survival_list_api:
    path: packages/grpc_survival_list_api
  intl: ^0.17.0
  protobuf: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  survival_list_api:
    path: packages/survival_list_api
  survival_list_repository:
    path: packages/survival_list_repository

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
