name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.5
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  # Unfortunately, a breaking change was introduced in 4.5.2.
  # https://github.com/firebase/flutterfire/issues/9806
  firebase_core_platform_interface: ^4.5.3
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.2
  meta: ^1.8.0

dev_dependencies:
  firebase_auth_platform_interface: ^6.10.4
  plugin_platform_interface: ^2.1.3
  very_good_analysis: ^4.0.0+1
