name: survival_list_repository
description: A repository that handles Survival List requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_repository:
    path: ../authentication_repository
  equatable: ^2.0.5
  generated_grpc_api:
    path: ../generated_grpc_api
  grpc: ^3.1.0
  meta: ^1.8.0
  protobuf: ^2.1.0
  rxdart: ^0.27.7

dev_dependencies:
  very_good_analysis: ^5.0.0+1
