name: survival_list_repository
description: A repository that handles Survival List requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  rxdart: ^0.27.7
  survival_list_api:
    path: ../survival_list_api

dev_dependencies:
  very_good_analysis: ^4.0.0
