targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - proto/**
    builders:
      protoc_builder:
        options:
          out_dir: "lib/generated"
          grpc: true
          use_installed_protoc: true
