[package]
name = "server"
version = "0.1.0"
edition = "2021"

[profile.dev.package.sqlx-macros]
opt-level = 3

[dependencies]
anyhow = "1.0.68"
dotenvy = "0.15.6"
pretty_env_logger = "0.4.0"
prost = "0.11.6"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres", "time", "migrate", "tls", "offline"] }
tokio = { version = "1.24.2", features = ["full"] }
tonic = "0.8.3"
tonic-reflection = "0.6.0"

[build-dependencies]
dotenvy = "0.15.6"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres", "time", "migrate", "tls", "offline"] }
tokio = { version = "1.24.2", features = ["full"] }
tonic-build = "0.8.4"
