[package]
name = "server"
version = "0.1.0"
edition = "2021"

[profile.dev.package.sqlx-macros]
opt-level = 3

[dependencies]
axum = "0.6.4"
dotenvy = "0.15.6"
hyper = { version = "0.14.23", features = ["full"] }
pretty_env_logger = "0.4.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres", "time", "migrate", "tls", "offline"] }
tokio = { version = "1.24.2", features = ["full"] }

[build-dependencies]
dotenvy = "0.15.6"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres", "time", "migrate", "tls", "offline"] }
tokio = { version = "1.24.2", features = ["full"] }
