[package]
name = "server"
version = "0.1.1"
edition = "2021"

[profile.dev.package.sqlx-macros]
opt-level = 3

[dependencies]
anyhow = "1.0.69"
dotenvy = "0.15.6"
futures-core = "0.3.27"
futures-util = "0.3.27"
jsonwebtoken = "8.3.0"
log = "0.4.17"
pretty_env_logger = "0.4.0"
prost = "0.11.8"
reqwest = { version = "0.11.14", features = ["rustls-tls", "json"], default-features = false }
serde = { version = "1.0.156", features = ["derive"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres", "time", "migrate", "tls", "offline", "uuid"] }
tokio = { version = "1.26.0", features = ["full"] }
tokio-stream = "0.1.12"
tonic = { version = "0.8.3", features = ["gzip", "tokio-rustls"] }

[build-dependencies]
dotenvy = "0.15.6"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres", "time", "migrate", "tls", "offline", "uuid"] }
tokio = { version = "1.26.0", features = ["full"] }
tonic-build = "0.8.4"
