apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: survival-list-server
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/bjarkebjarke/survival-list-server
          env:
            - name: TARGET
              value: "Rust Sample v1"
