ALTER TABLE categories
	ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE GROUPS
	ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE recurrences
	ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE subcategories
	ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tasks
	ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
	ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users_groups
	ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

