name: survival_list_api
description: The interface and models for an API providing access to the Survival List server.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  authentication_repository:
    path: ../authentication_repository
  equatable: ^2.0.5
  grpc: ^3.1.0
  meta: ^1.8.0
  protobuf: ^2.1.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.3.3
  protoc_builder: ^0.3.1
  very_good_analysis: ^4.0.0
