name: deploy-server
run-name: Deploying survival-list server

on:
  push:
    branches:
      - deploy-server
    paths:
      - "server/**"
      - ".github/workflows/deploy-server.yml"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate-protos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: deploy-server

      - uses: actions/checkout@v3
        with:
          ref: server-production
          path: server-production

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "deploy-server/proto"

      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "deploy-server/proto"
          against: "server-production/proto"

  fly-io-deploy:
    runs-on: ubuntu-latest

    needs: validate-protos

    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions@v2
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_PROJECT_PATH: server
        with:
          args: "deploy"

  update-server-production-tag:
    runs-on: ubuntu-latest

    needs: fly-io-deploy

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: server-production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
