name: deploy-android-internal-testing
run-name: Deploy client to Play Store internal testing track

on:
  push:
    branches:
      - production
    paths:
      - "client/pubspec.yaml"
      - ".github/workflows/deploy-android-internal-testing.yml"

jobs:
  validate-version-bumped:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: android-client-internal-testing

      - id: current-version
        uses: jbutcher5/read-yaml@1.6
        with:
          file: "./client/pubspec.yaml"
          key-path: '["version"]'

      - uses: actions/checkout@v3

      - id: new-version
        uses: jbutcher5/read-yaml@1.6
        with:
          file: "./client/pubspec.yaml"
          key-path: '["version"]'

      - run: test $(printf '${{ steps.new-version.outputs.data }}\n${{ steps.current-version.outputs.data }}' | sort -V | head -n1) != '${{ steps.new-version.outputs.data }}'

  validate-server-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: production

      - uses: actions/checkout@v3
        with:
          ref: server-production
          path: server-production

      - uses: bufbuild/buf-setup-action@v1

      - name: Check that new client API is not ahead of server API
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: "server-production/proto"
          against: "production/proto"

  build-and-deploy:
    runs-on: ubuntu-latest

    needs:
      - validate-version-bumped
      - validate-server-api

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3

      # - name: Set up JDK 1.8
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8

      # - name: Build
      #   run: ./gradlew build

      # - name: Assemble Release Bundle
      #   run: |
      #     ./gradlew bundleRelease

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter build appbundle

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: client/build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.PLAY_STORE_SIGNING_KEY }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to internal testing
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJson: service_account.json
          packageName: dk.bjarkebjarke.survival_list
          releaseFiles: client/build/app/outputs/bundle/release/app-release.aab
          track: internal-testing
          whatsNewDirectory: client/whatsnew
          mappingFile: client/build/app/outputs/mapping/release/mapping.txt
          debugSymbols: client/build/app/intermediates/merged_native_libs/release/out/lib

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: android-client-internal-testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
