name: deploy-web
run-name: Deploying survival-list web client

on:
  push:
    branches:
      - production
    paths:
      - "client/**"

steps:
  - uses: actions/checkout@v3
  - uses: subosito/flutter-action@v2
    with:
      channel: "stable"
  - run: flutter pub get
  - run: flutter build web
