name: deploy-server
run-name: Deploying survival-list server
on:
  push:
    branches:
      - production
jobs:
  gcloud-deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/730713275888/locations/global/workloadIdentityPools/survival-list-service-account/providers/github"
          service_account: "survival-list-service-account@survival-list-server.iam.gserviceaccount.com"

      - name: Deploy to Cloud Run
        id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "survival-list-server"
          region: "europe-north1"
          source: "./server/"

      # - id: "deploy"
      #   uses: "google-github-actions/deploy-appengine@v1"
      #   with:
      #     working_directory: server

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
