name: Deploy to Play Store internal testing track

on:
  push:
    branches:
      - production
    paths:
      - "client/pubspec.yaml"
      - ".github/workflows/deploy-android-internal-testing.yml"

jobs:
  validate-protos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: production

      - uses: actions/checkout@v3
        with:
          ref: server-production
          path: server-production

      - uses: bufbuild/buf-setup-action@v1

      - name: Check that new client API is not ahead of server API
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: "server-production/proto"
          against: "production/proto"

  build-and-deploy:
    runs-on: ubuntu-latest

    needs: validate-protos

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3

      # - name: Set up JDK 1.8
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8

      # - name: Build
      #   run: ./gradlew build

      # - name: Assemble Release Bundle
      #   run: |
      #     ./gradlew bundleRelease

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter build appbundle

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to internal testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: dk.bjarkebjarke.survival_list
          releaseFile: build/app/outputs/bundle/release/app-release.aab
          track: internal-testing
          whatsNewDirectory: whatsnew
          mappingFile: build/app/outputs/mapping/release/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/release/out/lib

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: android-client-internal-testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
